# Workflow to continuously run the test suite.

name: test

# Run on every push to the main branch, but only when go files are changed.
# Also run on pull requests that modify some go files.
on:
   push:
      branches:
         - main
      paths:
         - "**.go"

   pull_request:
      paths:
         - "**.go"

jobs:
   test:
      name: Test suite and Coverage

      runs-on: ubuntu-latest

      steps:
         -  name: Checkout
            uses: actions/checkout@v2

         -  name: Unshallow
            run: git fetch --prune --unshallow

         -  name: Set up Go
            uses: actions/setup-go@v2
            with:
               go-version: 1.14.x
            id: go

         -  name: Generate coverage
            run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

         -  name: Install goveralls
            env:
               GO111MODULE: off
            run: go get github.com/mattn/goveralls

         -  name: Send coverage
            env:
               COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: goveralls -coverprofile=coverage.out -service=github
